<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-12-05T17:18:09+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.4',
    'version_db_installed' => '20200609145307',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1607185058,
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
];
