<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-12-05T17:15:59+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'plasticseurope',
        ],
    ],
];
